Update Makefile
changing from LDFLAGS to LDLIB.

LDFLAGS should be for local libs, and LDLIB for c libraries.

here's what happens before change:

make echo
gcc -Wall -O2 -ffast-math -fsingle-precision-constant   -lm  gensin.c   -o gensin
/usr/bin/ld: /tmp/cc9qUBLv.o: in function `main':
gensin.c:(.text.startup+0x5d): undefined reference to `sin'
collect2: error: ld returned 1 exit status
make: *** [<builtin>: gensin] Error 1

and after:

$ make echo
gcc -Wall -O2 -ffast-math -fsingle-precision-constant     gensin.c  -lm -o gensin
./gensin > gensin.h
gcc -Wall -O2 -ffast-math -fsingle-precision-constant    -c -o convert.o convert.c
gcc   convert.o  -lm -o convert
./convert echo 0.3 0.3 0.3 0.3 < input.raw > output.raw
Playing echo(0.300000,0.300000,0.300000,0.300000)
echo: delay=300 ms lfo=1.2 ms feedback=0.3
ffmpeg -y -v fatal -f s32le -ar 48000 -ac 1 -i output.raw -f mp3 echo.mp3
aplay -q -c1 -r 48000 -f s32 output.raw

(and i hear the cool echo bass scale)